def liebiao():
    '''增删查改
    append,insert,remove,
    '''
    fruits=['apple','banner','orange']
    #f-string（格式化字符串字面量）,如果不使用的话，就通过+的方案进行拼接
    print(f"原始列表：{fruits}")
    #访问元素，第一个水果，最后一个水果
    print(f"第一个水果：{fruits[0]}")
    print(f"第一个水果：{fruits[-1]}")
    #添加元素
    fruits.append('葡萄')
    print(f"添加后：{fruits}")
    #在某个索引中加入元素
    fruits.insert(1,'西瓜')
    print(f'添加后:{fruits}')
    #修改元素
    fruits[2]='哈密瓜'
    print(f'修改后：{fruits}')
    #删除元素
    fruits.remove('西瓜')
    print(f"删除后：{fruits}")
    #删除并返回最后一个
    popped=fruits.pop()
    print(f"pop后：{fruits}，被删除的：{popped}")
    #切片
    print(f'前两个元素：{fruits[:2]}')
    print(f'从索引1开始：{fruits[1:]}')
    #遍历列表
    print('遍历列表：')
    for fruit in fruits:
        print(f'---{fruit}')
    #常用方法
    numbers=[2,4,10,3,0,1]
    #排序
    numbers.sort()
    print(f'排序后：{numbers}')
    #反转
    numbers.reverse()
    print(f'反转后：{numbers}')
    print(f'列表长度：{len(numbers)}')
if __name__ == '__main__':
    liebiao()