[pytest]

# 测试用例目录
testpaths = testcase


# 测试文件规则
python_files = test_*.py


# 测试类规则
python_classes = Test*


# 测试方法规则
python_functions = test_*


# 命令行参数
addopts =
    -vs


# 控制台显示日志
log_cli = true


# 日志级别
log_cli_level = INFO


# 解决pytest参数化中文名称显示问题
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True