[pytest]
#pytest配置，无需修改
# 用例路径
testpaths = test_cases
# 用例文件命名规则
python_files = test_*.py
# 用例类命名规则
python_classes = Test*
# 用例方法命名规则
python_functions = test_*
# 运行参数：详细日志、生成Allure报告
; addopts = -v --alluredir=./reports/allure-results --clean-alluredir
addopts = -v --html=./reports/simple_report.html