Environment=Test Environment
    Project=Official Website API Automation
    ApiUrl=https://api-t.flextv.cc
    FrontendUrl=https://www-h5.flextv9.com
    Framework=Python + Pytest
    Report=Allure
    RequestType=HTTP
    TokenMode=Fixed Token
    TestMode=Guest