# ????
company=XX??????
project=???????????
team=???-??????
# ????
test_env=?????
base_url=http://pre.api.xxcompany.com
test_version=V2.1.0
executor=???????
test_date=2026-03-18
# ?????
remark=????/??/?????????Token???????????????